### ISSUE TITLE
Enhancements

### ISSUE THREAD

**Issue by sayem314** [orzhtml/react-native-orzhtml-htmlview#1]
- Add at least one screenshots from demo/example project.
- Improve the readme with better info about each props and how to customise them.

**Comment by orzhtml** [comment]
demo:
https://github.com/orzhtml/react-native-orzhtml-htmlview/tree/master/example

**Comment by sayem314** [comment]
I saw the example folder before. What I mean is, create dew screenshot and add it to readme.

**Comment by orzhtml** [comment]
> I saw the example folder before. What I mean is, create dew screenshot and add it to readme.

Thanks to remind, readme already add the screenshots

**Comment by sayem314** [comment]
Is there any possibility to support table as well? Also it would be nice if you add supported tags on readme 🙂

**Comment by orzhtml** [comment]
> Is there any possibility to support table as well? Also it would be nice if you add supported tags on readme

TODO: 
Base label style:   table, ul, ol   
^_^

**Comment by orzhtml** [comment]
> Is there any possibility to support table as well? Also it would be nice if you add supported tags on readme

Welcome to the fork

**Comment by orzhtml** [comment]
update: table, ul, ol

version 1.0.2：
react-native-orzhtml-htmlview
