### ISSUE TITLE
Global color

### ISSUE THREAD

**Issue by sayem314** [orzhtml/react-native-orzhtml-htmlview#2]
globalColor is only applied on text, we need them on the bullet and other stuff as well

**Comment by orzhtml** [comment]
stylesheet

<HTMLView
   stylesheet={{
     a: { color: 'red' }
   }}
/>

**Comment by sayem314** [comment]
Thanks. But shouldn’t it respect the globalColor by default?

**Comment by orzhtml** [comment]
‘Stylesheet’ tag style rewrite  > globalColor  default
