### ISSUE TITLE
Invariant Violation: Invariant Violation: requireNativeComponent: "FastImageView" was not found in the UIManager.

### ISSUE THREAD

**Issue by sayem314** [orzhtml/react-native-orzhtml-htmlview#3]
![Screenshot_1566036394](https://user-images.githubusercontent.com/14138401/63209928-0dafc400-c109-11e9-97f8-ddcd603ed727.png)

**Comment by orzhtml** [comment]
For React Native 0.60.0 or higher.

npm install react-native-fast-image --save or yarn add react-native-fast-image

For React Native <= 0.59.x use version 6.1.1 or lower

npm install react-native-fast-image@6.1.1 --save or yarn add react-native-fast-image@6.1.1

**Comment by sayem314** [comment]
But it’s already on package.json

Edit: I guess I need 7.x branch. Will try that, thanks.

**Comment by orzhtml** [comment]
package.json

remove: 

    "react-native-fast-image": "6.1.1",
    "react-native-video": "^5.0.0",
