### ISSUE TITLE
Global text styling

### ISSUE THREAD

**Issue by sayem314** [orzhtml/react-native-orzhtml-htmlview#4]
How do I change the global text config? Current font-family have too much space and size is kinda large.

**Comment by orzhtml** [comment]
I'm sorry, There is no global text config

change font-family：

stylesheet

```
<HTMLView
  stylesheet={{
    strong: { fontFamily: 'xxx' },
    span: { fontFamily: 'xxx' },
    a: { fontFamily: 'xxx' }
    ......
  }}
/>
```

welcome fork,  pull requests
